# 1.0 Introducción a Numpy

Biblioteca de Python comúnmente usada en la ciencia de datos.

**Numpy**

- Sencilla de usar
- Adecuada para el manejo de arreglos
- Rápida

_________________

## Librería

Empecemos con importando la librería

In [1]:
import numpy as np

## Manejo de arreglos con Numpy

Empecemos con los arreglos, estos pueden ser vectores, matrices, tensores, etc... <br>
Para declararlos escribimos:

In [2]:
np.array([10, 20, 24, 5, 15, 50])

array([10, 20, 24,  5, 15, 50])

Para acceder a las listas, utilizamos el slice notation mediante el uso de corchetes, por ejemplo:

In [3]:
a = np.array([10, 30, 51, 100, 8, 63])

# Access an element with index 4
a[4]

8

In [4]:
# Sublist with a start index of 3
a[3:]

array([100,   8,  63])

In [5]:
# Sublist with a start of index 3 and end of index 7
a[3:7]

array([100,   8,  63])

In [6]:
# Sublist with a start index of 1 and a step of 2
a[1::2]

array([ 30, 100,  63])

También podemos crear arreglos de una manera dinámica. Veamos diferentes funciones:

In [7]:
# Array filled with zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
# Array filled with ones by a given dimension
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# Type of the argument
type(np.ones((4, 5)))

numpy.ndarray

In [10]:
# Array with elements distributed homogeneously over a specified interval
np.linspace(3,10,5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [11]:
# 2-D array
b = np.array([['x', 'y', 'z'], ['a', 'b', 'c']])
print(b)
type(b)

[['x' 'y' 'z']
 ['a' 'b' 'c']]


numpy.ndarray

In [12]:
# Number of dimensions
b.ndim

2

In [13]:
c = [12, 40, 1, 4, 7, 97, 38, 87, 18, 48]

# Sort the array
np.sort(c)

array([ 1,  4,  7, 12, 18, 38, 40, 48, 87, 97])

Podemos asignar una cabecera (header) a nuestros datos

In [14]:
header = [('name', 'S10'), ('age', int)]  # 'S10' means a string of size 10
data = [('Juan', 10), ('Maria', 70), ('Javier', 19), ('Luis', 80)]
users = np.array(data, dtype=header)

np.sort(users, order='age')

array([(b'Juan', 10), (b'Javier', 19), (b'Maria', 70), (b'Luis', 80)],
      dtype=[('name', 'S10'), ('age', '<i8')])

In [15]:
# Array with evenly spaced elements
np.arange(25)  # Doesn't include 25

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
# Array with evenly spaced elements by a given interval
np.arange(5, 30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
# Array with evenly spaced elements by a given interval and a step
np.arange(5, 50, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [18]:
# Array with a given dimension filled with only one value
np.full((3,5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [19]:
# Array with the given values of the diagonal
np.diag([0, 3, 9, 10])

array([[ 0,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 10]])